const characters = {
  amox: {
    name: "Amox Velthune",
    title: "The Lore Keeper",
    theme: "theme-wizard",
    accentColor: "#8b7dd8",
    accentColorRgb: "139, 125, 216",
    race: "Half-Elf",
    class: "Wizard",
    subclass: "School of Divination",
    level: 6,
    alignment: "Lawful Neutral",
    abilities: {
      STR: 8,
      DEX: 14,
      CON: 14,
      INT: 18,
      WIS: 12,
      CHA: 8,
    },
    hp: 38,
    ac: 12,
    speed: 30,
    proficiencyBonus: 3,
    initiative: 2,
    savingThrows: {
      str: { bonus: -1, proficient: false },
      dex: { bonus: 2, proficient: false },
      con: { bonus: 2, proficient: false },
      int: { bonus: 7, proficient: true },
      wis: { bonus: 4, proficient: true },
      cha: { bonus: -1, proficient: false },
    },
    senses: ["Darkvision 60 ft.", "Passive Perception 14"],
    languages: ["Common", "Elvish", "Draconic", "Dwarvish"],
    proficiencies: {
      armor: ["None"],
      weapons: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
      tools: ["None"],
    },
    attacks: [
      {
        name: "Quarterstaff",
        bonus: -1,
        damage: "1d6-1 bludgeoning",
        notes: "Two-handed: 1d8-1",
      },
      {
        name: "Fire Bolt (cantrip)",
        bonus: 7,
        damage: "2d10 fire",
        notes: "Ranged spell attack, 120 ft.",
      },
    ],
    skills: [
      { name: "Acrobatics", bonus: 2, proficient: false },
      { name: "Animal Handling", bonus: 1, proficient: false },
      { name: "Arcana", bonus: 7, proficient: true },
      { name: "Athletics", bonus: -1, proficient: false },
      { name: "Deception", bonus: -1, proficient: false },
      { name: "History", bonus: 7, proficient: true },
      { name: "Insight", bonus: 4, proficient: true },
      { name: "Intimidation", bonus: -1, proficient: false },
      { name: "Investigation", bonus: 7, proficient: true },
      { name: "Medicine", bonus: 1, proficient: false },
      { name: "Nature", bonus: 4, proficient: false },
      { name: "Perception", bonus: 4, proficient: true },
      { name: "Performance", bonus: -1, proficient: false },
      { name: "Persuasion", bonus: -1, proficient: false },
      { name: "Religion", bonus: 4, proficient: false },
      { name: "Sleight of Hand", bonus: 2, proficient: false },
      { name: "Stealth", bonus: 2, proficient: false },
      { name: "Survival", bonus: 1, proficient: false },
    ],
    features: [
      "Portent: Roll 2d20 after long rest, replace any roll during the day",
      "Arcane Recovery: Recover spell slots during short rest (up to level 3)",
      "Darkvision: 60 ft",
      "Fey Ancestry: Advantage vs charm, immune to sleep magic",
      "Ritual Casting: Cast wizard spells as rituals",
    ],
    equipment: [
      "Spellbook",
      "Arcane focus (crystal orb)",
      "Lens of Translation (advantage on ancient texts)",
      "Component pouch",
      "Dagger",
      "Scholar's pack",
    ],
    spells: {
      cantrips: [
        {
          name: "Fire Bolt",
          level: "Cantrip",
          castingTime: "1 action",
          range: "120 feet",
          components: "V, S",
          duration: "Instantaneous",
          description:
            "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack. On a hit, the target takes 2d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried.",
        },
        {
          name: "Mage Hand",
          level: "Cantrip",
          castingTime: "1 action",
          range: "30 feet",
          components: "V, S",
          duration: "1 minute",
          description:
            "A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration. You can use your action to control the hand, using it to manipulate objects, open unlocked doors or containers, stow or retrieve items, or pour contents out of a vial. The hand can't attack, activate magic items, or carry more than 10 pounds.",
        },
        {
          name: "Prestidigitation",
          level: "Cantrip",
          castingTime: "1 action",
          range: "10 feet",
          components: "V, S",
          duration: "Up to 1 hour",
          description:
            "This spell is a minor magical trick. You create an instantaneous, harmless sensory effect, light or snuff out a candle/torch/small campfire, clean or soil an object, chill/warm/flavor nonliving material, make a color/small mark/symbol appear, or create a nonmagical trinket or illusory image that fits in your hand.",
        },
        {
          name: "Message",
          level: "Cantrip",
          castingTime: "1 action",
          range: "120 feet",
          components: "V, S, M (a short piece of copper wire)",
          duration: "1 round",
          description:
            "You point your finger toward a creature within range and whisper a message. The target (and only the target) hears the message and can reply in a whisper that only you can hear. You can cast this spell through solid objects if you are familiar with the target and know it is beyond the barrier.",
        },
      ],
      level1: [
        {
          name: "Detect Magic",
          level: "1st-level",
          castingTime: "1 action (Ritual)",
          range: "Self",
          components: "V, S",
          duration: "Concentration, up to 10 minutes",
          ritual: true,
          description:
            "For the duration, you sense the presence of magic within 30 feet. If you sense magic, you can use your action to see a faint aura around any visible creature or object that bears magic, and you learn its school of magic, if any. The spell penetrates most barriers but is blocked by 1 foot of stone, 1 inch of common metal, thin sheet of lead, or 3 feet of wood or dirt.",
        },
        {
          name: "Identify",
          level: "1st-level",
          castingTime: "1 minute (Ritual)",
          range: "Touch",
          components: "V, S, M (pearl worth 100gp)",
          duration: "Instantaneous",
          ritual: true,
          description:
            "You choose one object that you must touch throughout the casting. If it's a magic item or magical object, you learn its properties, how to use them, whether it requires attunement, how many charges it has, and what spells are affecting it. If the item was created by a spell, you learn which spell. If you touch a creature, you learn what spells are currently affecting it.",
        },
        {
          name: "Comprehend Languages",
          level: "1st-level",
          castingTime: "1 action (Ritual)",
          range: "Self",
          components: "V, S, M (soot and salt)",
          duration: "1 hour",
          ritual: true,
          description:
            "For the duration, you understand the literal meaning of any spoken language that you hear. You also understand any written language that you see, but you must be touching the surface on which the words are written. It takes about 1 minute to read one page of text. This spell doesn't decode secret messages or glyphs that aren't part of a written language.",
        },
        {
          name: "Mage Armor",
          level: "1st-level",
          castingTime: "1 action",
          range: "Touch",
          components: "V, S, M (piece of cured leather)",
          duration: "8 hours",
          description:
            "You touch a willing creature who isn't wearing armor, and a protective magical force surrounds it until the spell ends. The target's base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.",
        },
        {
          name: "Shield",
          level: "1st-level",
          castingTime: "1 reaction",
          range: "Self",
          components: "V, S",
          duration: "1 round",
          description:
            "An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.",
        },
        {
          name: "Find Familiar",
          level: "1st-level",
          castingTime: "1 hour (Ritual)",
          range: "10 feet",
          components: "V, S, M (10gp worth of charcoal, incense, and herbs)",
          duration: "Instantaneous",
          ritual: true,
          description:
            "You gain the service of a familiar, a spirit that takes an animal form you choose: bat, cat, crab, frog, hawk, lizard, octopus, owl, poisonous snake, fish, rat, raven, sea horse, spider, or weasel. Your familiar acts independently of you, but it always obeys your commands. In combat, it rolls its own initiative and acts on its own turn.",
        },
      ],
      level2: [
        {
          name: "Detect Thoughts",
          level: "2nd-level",
          castingTime: "1 action",
          range: "Self",
          components: "V, S, M (copper piece)",
          duration: "Concentration, up to 1 minute",
          description:
            "For the duration, you can read the thoughts of certain creatures. When you cast the spell, choose one creature that you can see within 30 feet. You learn the surface thoughts of the creature—what is most on its mind in that moment. As an action, you can shift your attention to another creature's thoughts.",
        },
        {
          name: "Locate Object",
          level: "2nd-level",
          castingTime: "1 action",
          range: "Self",
          components: "V, S, M (forked twig)",
          duration: "Concentration, up to 10 minutes",
          description:
            "Describe or name an object that is familiar to you. You sense the direction to the object's location, as long as that object is within 1,000 feet of you. If the object is in motion, you know the direction of its movement.",
        },
        {
          name: "Misty Step",
          level: "2nd-level",
          castingTime: "1 bonus action",
          range: "Self",
          components: "V",
          duration: "Instantaneous",
          description:
            "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.",
        },
        {
          name: "Suggestion",
          level: "2nd-level",
          castingTime: "1 action",
          range: "30 feet",
          components: "V, M (snake's tongue, honeycomb)",
          duration: "Concentration, up to 8 hours",
          description:
            "You suggest a course of activity (limited to a sentence or two) and magically influence a creature you can see within range that can hear and understand you. The suggestion must be worded in such a manner as to make the course of action sound reasonable. The target must make a Wisdom saving throw. On a failed save, it pursues the course of action you described to the best of its ability.",
        },
      ],
      level3: [
        {
          name: "Counterspell",
          level: "3rd-level",
          castingTime: "1 reaction",
          range: "60 feet",
          components: "S",
          duration: "Instantaneous",
          description:
            "You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails. If it's casting a spell of 4th level or higher, make an ability check using your spellcasting ability (DC 10 + spell's level). On a success, the creature's spell fails and has no effect.",
        },
        {
          name: "Fireball",
          level: "3rd-level",
          castingTime: "1 action",
          range: "150 feet",
          components: "V, S, M (tiny ball of bat guano and sulfur)",
          duration: "Instantaneous",
          description:
            "A bright streak flashes from your pointing finger to a point you choose within range and blossoms with a roar into an explosion of flame. Each creature in a 20-foot-radius sphere must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much on a successful one. The fire spreads around corners and ignites flammable objects that aren't being worn or carried.",
        },
        {
          name: "Dispel Magic",
          level: "3rd-level",
          castingTime: "1 action",
          range: "120 feet",
          components: "V, S",
          duration: "Instantaneous",
          description:
            "Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability. The DC equals 10 + the spell's level. On a successful check, the spell ends.",
        },
        {
          name: "Clairvoyance",
          level: "3rd-level",
          castingTime: "10 minutes (Ritual)",
          range: "1 mile",
          components: "V, S, M (focus worth 100gp)",
          duration: "Concentration, up to 10 minutes",
          ritual: true,
          description:
            "You create an invisible sensor within range in a location familiar to you or in an obvious location unfamiliar to you. The sensor remains for the duration. When you cast the spell, choose seeing or hearing. You can use the chosen sense through the sensor as if you were in its space. As an action, you can switch between seeing and hearing.",
        },
      ],
    },
    spellSlots: {
      level1: { total: 4, available: 4 },
      level2: { total: 3, available: 3 },
      level3: { total: 3, available: 3 },
    },
    spellSaveDC: 15,
    spellAttackBonus: 7,
    hitDie: 6,
    shortRestResources: [
      { name: "Portent Dice", uses: 2, restType: "long" },
      { name: "Arcane Recovery", uses: 1, restType: "long" },
    ],
  },
  barak: {
    name: "Barak",
    title: "The Anchor",
    theme: "theme-cleric",
    accentColor: "#f59e0b",
    accentColorRgb: "245, 158, 11",
    race: "Mountain Dwarf",
    class: "Cleric",
    subclass: "Life Domain",
    level: 6,
    alignment: "Lawful Good",
    abilities: {
      STR: 16,
      DEX: 10,
      CON: 16,
      INT: 10,
      WIS: 16,
      CHA: 12,
    },
    hp: 52,
    ac: 18,
    speed: 25,
    proficiencyBonus: 3,
    initiative: 0,
    savingThrows: {
      str: { bonus: 3, proficient: false },
      dex: { bonus: 0, proficient: false },
      con: { bonus: 6, proficient: true },
      int: { bonus: 0, proficient: false },
      wis: { bonus: 6, proficient: true },
      cha: { bonus: 4, proficient: true },
    },
    senses: ["Darkvision 60 ft.", "Passive Perception 13"],
    languages: ["Common", "Dwarvish"],
    proficiencies: {
      armor: ["Light Armor", "Medium Armor", "Heavy Armor", "Shields"],
      weapons: ["Simple Weapons", "Battleaxe", "Handaxe", "Light Hammer", "Warhammer"],
      tools: ["Smith's Tools", "Brewer's Supplies", "Mason's Tools"],
    },
    attacks: [
      {
        name: "Warhammer",
        bonus: 6,
        damage: "1d8+3 bludgeoning",
        notes: "Versatile: 1d10+3",
      },
      {
        name: "Sacred Flame (cantrip)",
        bonus: null,
        damage: "2d8 radiant",
        notes: "DEX save DC 14, 60 ft.",
      },
    ],
    skills: [
      { name: "Acrobatics", bonus: 0, proficient: false },
      { name: "Animal Handling", bonus: 3, proficient: false },
      { name: "Arcana", bonus: 0, proficient: false },
      { name: "Athletics", bonus: 6, proficient: true },
      { name: "Deception", bonus: 1, proficient: false },
      { name: "History", bonus: 0, proficient: false },
      { name: "Insight", bonus: 6, proficient: true },
      { name: "Intimidation", bonus: 1, proficient: false },
      { name: "Investigation", bonus: 0, proficient: false },
      { name: "Medicine", bonus: 6, proficient: true },
      { name: "Nature", bonus: 0, proficient: false },
      { name: "Perception", bonus: 3, proficient: false },
      { name: "Performance", bonus: 1, proficient: false },
      { name: "Persuasion", bonus: 1, proficient: false },
      { name: "Religion", bonus: 3, proficient: true },
      { name: "Sleight of Hand", bonus: 0, proficient: false },
      { name: "Stealth", bonus: 0, proficient: false },
      { name: "Survival", bonus: 3, proficient: false },
    ],
    features: [
      "Disciple of Life: Healing spells restore +2 + spell level HP",
      "Channel Divinity: Preserve Life (30 HP pool to distribute)",
      "Channel Divinity: Turn Undead",
      "Destroy Undead (CR 1/2 or lower)",
      "Darkvision: 60 ft",
      "Dwarven Resilience: Advantage vs poison, resistance to poison damage",
    ],
    equipment: [
      "Warhammer",
      "Shield with holy symbol",
      "Chain mail",
      "Amulet of the Steadfast (reduce to 1 HP instead of 0, 1/long rest)",
      "Holy symbol",
      "Prayer book",
      "Healer's kit",
    ],
    spells: {
      cantrips: [
        {
          name: "Sacred Flame",
          level: "Cantrip",
          castingTime: "1 action",
          range: "60 feet",
          components: "V, S",
          duration: "Instantaneous",
          description:
            "Flame-like radiance descends on a creature you can see within range. The target must succeed on a Dexterity saving throw or take 2d8 radiant damage. The target gains no benefit from cover for this saving throw.",
        },
        {
          name: "Spare the Dying",
          level: "Cantrip",
          castingTime: "1 action",
          range: "Touch",
          components: "V, S",
          duration: "Instantaneous",
          description:
            "You touch a living creature that has 0 hit points. The creature becomes stable. This spell has no effect on undead or constructs.",
        },
        {
          name: "Guidance",
          level: "Cantrip",
          castingTime: "1 action",
          range: "Touch",
          components: "V, S",
          duration: "Concentration, up to 1 minute",
          description:
            "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the check.",
        },
      ],
      level1: [
        {
          name: "Cure Wounds",
          level: "1st-level",
          castingTime: "1 action",
          range: "Touch",
          components: "V, S",
          duration: "Instantaneous",
          description:
            "A creature you touch regains hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs. With Disciple of Life, this heals 1d8 + WIS modifier + 3.",
        },
        {
          name: "Healing Word",
          level: "1st-level",
          castingTime: "1 bonus action",
          range: "60 feet",
          components: "V",
          duration: "Instantaneous",
          description:
            "A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs. With Disciple of Life, this heals 1d4 + WIS modifier + 3.",
        },
        {
          name: "Bless",
          level: "1st-level (Domain)",
          castingTime: "1 action",
          range: "30 feet",
          components: "V, S, M (holy water)",
          duration: "Concentration, up to 1 minute",
          description:
            "You bless up to three creatures within range. Whenever a target makes an attack roll or saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw.",
        },
        {
          name: "Shield of Faith",
          level: "1st-level",
          castingTime: "1 bonus action",
          range: "60 feet",
          components: "V, S, M (parchment with holy text)",
          duration: "Concentration, up to 10 minutes",
          description:
            "A shimmering field appears and surrounds a creature of your choice within range, granting it a +2 bonus to AC for the duration.",
        },
      ],
      level2: [
        {
          name: "Spiritual Weapon",
          level: "2nd-level",
          castingTime: "1 bonus action",
          range: "60 feet",
          components: "V, S",
          duration: "1 minute",
          description:
            "You create a floating, spectral weapon within range that lasts for the duration. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes 1d8 + spellcasting ability modifier force damage. As a bonus action on your turn, you can move the weapon up to 20 feet and repeat the attack.",
        },
        {
          name: "Lesser Restoration",
          level: "2nd-level (Domain)",
          castingTime: "1 action",
          range: "Touch",
          components: "V, S",
          duration: "Instantaneous",
          description:
            "You touch a creature and can end either one disease or one condition afflicting it. The condition can be blinded, deafened, paralyzed, or poisoned.",
        },
        {
          name: "Aid",
          level: "2nd-level",
          castingTime: "1 action",
          range: "30 feet",
          components: "V, S, M (tiny strip of white cloth)",
          duration: "8 hours",
          description:
            "Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target's hit point maximum and current hit points increase by 5 for the duration.",
        },
      ],
      level3: [
        {
          name: "Revivify",
          level: "3rd-level (Domain)",
          castingTime: "1 action",
          range: "Touch",
          components: "V, S, M (diamonds worth 300gp, consumed)",
          duration: "Instantaneous",
          description:
            "You touch a creature that has died within the last minute. That creature returns to life with 1 hit point. This spell can't return to life a creature that has died of old age, nor can it restore missing body parts.",
        },
        {
          name: "Beacon of Hope",
          level: "3rd-level (Domain)",
          castingTime: "1 action",
          range: "30 feet",
          components: "V, S",
          duration: "Concentration, up to 1 minute",
          description:
            "You bestow hope on creatures within range. For the duration, each target has advantage on Wisdom saving throws and death saving throws, and regains the maximum number of hit points possible from any healing.",
        },
        {
          name: "Spirit Guardians",
          level: "3rd-level",
          castingTime: "1 action",
          range: "Self (15-foot radius)",
          components: "V, S, M (holy symbol)",
          duration: "Concentration, up to 10 minutes",
          description:
            "You call spirits to protect you. They flit around you to a distance of 15 feet. When a creature enters the area for the first time on a turn or starts its turn there, it must make a Wisdom saving throw. On a failed save, the creature takes 3d8 radiant damage. On a successful save, half damage. The area is difficult terrain for hostile creatures.",
        },
      ],
    },
    spellSlots: {
      level1: { total: 4, available: 4 },
      level2: { total: 3, available: 3 },
      level3: { total: 3, available: 3 },
    },
    spellSaveDC: 14,
    spellAttackBonus: 6,
    hitDie: 8,
    shortRestResources: [{ name: "Channel Divinity", uses: 2, restType: "short" }],
  },
  tenoch: {
    name: "Tenoch",
    title: "The Silent Guardian",
    theme: "theme-paladin",
    accentColor: "#60a5fa",
    accentColorRgb: "96, 165, 250",
    race: "Goliath",
    class: "Paladin",
    subclass: "Oath of Redemption",
    level: 6,
    alignment: "Neutral Good",
    abilities: {
      STR: 16,
      DEX: 10,
      CON: 16,
      INT: 8,
      WIS: 12,
      CHA: 14,
    },
    hp: 58,
    ac: 18,
    speed: 30,
    proficiencyBonus: 3,
    initiative: 0,
    savingThrows: {
      str: { bonus: 3, proficient: false },
      dex: { bonus: 0, proficient: false },
      con: { bonus: 3, proficient: false },
      int: { bonus: -1, proficient: false },
      wis: { bonus: 4, proficient: true },
      cha: { bonus: 5, proficient: true },
    },
    senses: ["Passive Perception 11"],
    languages: ["Common", "Giant"],
    proficiencies: {
      armor: ["Light Armor", "Medium Armor", "Heavy Armor", "Shields"],
      weapons: ["Simple Weapons", "Martial Weapons"],
      tools: ["None"],
    },
    attacks: [
      {
        name: "Maul",
        bonus: 6,
        damage: "2d6+3 bludgeoning",
        notes: "Two-handed, heavy",
      },
    ],
    skills: [
      { name: "Acrobatics", bonus: 0, proficient: false },
      { name: "Animal Handling", bonus: 1, proficient: false },
      { name: "Arcana", bonus: -1, proficient: false },
      { name: "Athletics", bonus: 6, proficient: true },
      { name: "Deception", bonus: 2, proficient: false },
      { name: "History", bonus: -1, proficient: false },
      { name: "Insight", bonus: 4, proficient: true },
      { name: "Intimidation", bonus: 2, proficient: false },
      { name: "Investigation", bonus: -1, proficient: false },
      { name: "Medicine", bonus: 4, proficient: true },
      { name: "Nature", bonus: -1, proficient: false },
      { name: "Perception", bonus: 1, proficient: false },
      { name: "Performance", bonus: 2, proficient: false },
      { name: "Persuasion", bonus: 5, proficient: true },
      { name: "Religion", bonus: -1, proficient: false },
      { name: "Sleight of Hand", bonus: 0, proficient: false },
      { name: "Stealth", bonus: 0, proficient: false },
      { name: "Survival", bonus: 1, proficient: false },
    ],
    features: [
      "Stone's Endurance: Reduce damage by 1d12+3 (1/short rest)",
      "Protection Fighting Style: Impose disadvantage on attack against ally",
      "Lay on Hands: 30 HP healing pool",
      "Divine Smite: Expend spell slot for extra radiant damage",
      "Aura of Protection: +2 to saving throws for allies within 10 ft",
      "Rebuke the Violent: Reflect damage back to attacker",
      "Powerful Build: Count as one size larger for carrying capacity",
    ],
    equipment: [
      "Maul",
      "Shield with protective runes",
      "Chain mail",
      "Bracers of Shielding (teleport to ally and grant resistance, 1/long rest)",
      "Holy symbol",
      "Healing potions (2)",
    ],
    spells: {
      level1: [
        {
          name: "Sanctuary",
          level: "1st-level (Oath)",
          castingTime: "1 bonus action",
          range: "30 feet",
          components: "V, S, M (small silver mirror)",
          duration: "1 minute",
          description:
            "You ward a creature within range against attack. Until the spell ends, any creature who targets the warded creature with an attack or harmful spell must first make a Wisdom saving throw. On a failed save, the creature must choose a new target or lose the attack or spell. This spell doesn't protect the warded creature from area effects. If the warded creature makes an attack or casts a spell, this spell ends.",
        },
        {
          name: "Sleep",
          level: "1st-level (Oath)",
          castingTime: "1 action",
          range: "90 feet",
          components: "V, S, M (sand, rose petals, or cricket)",
          duration: "1 minute",
          description:
            "This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose are affected in ascending order of their current hit points, ignoring unconscious creatures. Each affected creature falls unconscious until the spell ends, the sleeper takes damage, or someone uses an action to shake or slap the sleeper awake.",
        },
        {
          name: "Bless",
          level: "1st-level",
          castingTime: "1 action",
          range: "30 feet",
          components: "V, S, M (holy water)",
          duration: "Concentration, up to 1 minute",
          description:
            "You bless up to three creatures within range. Whenever a target makes an attack roll or saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw.",
        },
        {
          name: "Shield of Faith",
          level: "1st-level",
          castingTime: "1 bonus action",
          range: "60 feet",
          components: "V, S, M (parchment with holy text)",
          duration: "Concentration, up to 10 minutes",
          description:
            "A shimmering field appears and surrounds a creature of your choice within range, granting it a +2 bonus to AC for the duration.",
        },
      ],
      level2: [
        {
          name: "Hold Person",
          level: "2nd-level (Oath)",
          castingTime: "1 action",
          range: "60 feet",
          components: "V, S, M (small, straight piece of iron)",
          duration: "Concentration, up to 1 minute",
          description:
            "Choose a humanoid you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends. At Higher Levels: You can target one additional humanoid for each slot level above 2nd.",
        },
        {
          name: "Calm Emotions",
          level: "2nd-level (Oath)",
          castingTime: "1 action",
          range: "60 feet",
          components: "V, S",
          duration: "Concentration, up to 1 minute",
          description:
            "You attempt to suppress strong emotions in a group of people. Each humanoid in a 20-foot-radius sphere must make a Charisma saving throw. On a failed save, choose one: suppress charmed or frightened effects, or make targets indifferent about creatures they're hostile toward. The spell ends on an affected target if they're attacked or harmed by a spell or if they witness allies being harmed.",
        },
        {
          name: "Aid",
          level: "2nd-level",
          castingTime: "1 action",
          range: "30 feet",
          components: "V, S, M (tiny strip of white cloth)",
          duration: "8 hours",
          description:
            "Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target's hit point maximum and current hit points increase by 5 for the duration.",
        },
      ],
    },
    spellSlots: {
      level1: { total: 4, available: 4 },
      level2: { total: 2, available: 2 },
    },
    spellSaveDC: 13,
    spellAttackBonus: 5,
    hitDie: 10,
    shortRestResources: [
      { name: "Stone's Endurance", uses: 1, restType: "short" },
      { name: "Lay on Hands", uses: 30, restType: "long", pool: true },
    ],
  },
  glorg: {
    name: "Glorg",
    title: "The Wildfire",
    theme: "theme-rogue",
    accentColor: "#f87171",
    accentColorRgb: "248, 113, 113",
    race: "Goblin",
    class: "Rogue",
    subclass: "Arcane Trickster",
    level: 6,
    alignment: "Chaotic Good",
    abilities: {
      STR: 8,
      DEX: 18,
      CON: 14,
      INT: 14,
      WIS: 12,
      CHA: 10,
    },
    hp: 40,
    ac: 16,
    speed: 30,
    proficiencyBonus: 3,
    initiative: 4,
    savingThrows: {
      str: { bonus: -1, proficient: false },
      dex: { bonus: 7, proficient: true },
      con: { bonus: 2, proficient: false },
      int: { bonus: 5, proficient: true },
      wis: { bonus: 1, proficient: false },
      cha: { bonus: 0, proficient: false },
    },
    senses: ["Darkvision 60 ft.", "Passive Perception 14"],
    languages: ["Common", "Goblin"],
    proficiencies: {
      armor: ["Light Armor"],
      weapons: ["Simple Weapons", "Hand Crossbows", "Longswords", "Rapiers", "Shortswords"],
      tools: ["Thieves' Tools"],
    },
    attacks: [
      {
        name: "Shortsword (melee)",
        bonus: 7,
        damage: "1d6+4 piercing",
        notes: "Sneak Attack: +3d6",
      },
      {
        name: "Shortsword (offhand)",
        bonus: 7,
        damage: "1d6+4 piercing",
        notes: "Two-weapon fighting",
      },
      {
        name: "Shortbow",
        bonus: 7,
        damage: "1d6+4 piercing",
        notes: "Range 80/320, Sneak Attack: +3d6",
      },
    ],
    skills: [
      { name: "Acrobatics", bonus: 7, proficient: true },
      { name: "Animal Handling", bonus: 1, proficient: false },
      { name: "Arcana", bonus: 2, proficient: false },
      { name: "Athletics", bonus: -1, proficient: false },
      { name: "Deception", bonus: 3, proficient: true },
      { name: "History", bonus: 2, proficient: false },
      { name: "Insight", bonus: 1, proficient: false },
      { name: "Intimidation", bonus: 0, proficient: false },
      { name: "Investigation", bonus: 5, proficient: true },
      { name: "Medicine", bonus: 1, proficient: false },
      { name: "Nature", bonus: 2, proficient: false },
      { name: "Perception", bonus: 4, proficient: true },
      { name: "Performance", bonus: 0, proficient: false },
      { name: "Persuasion", bonus: 0, proficient: false },
      { name: "Religion", bonus: 2, proficient: false },
      { name: "Sleight of Hand", bonus: 7, proficient: true },
      { name: "Stealth", bonus: 10, proficient: true },
      { name: "Survival", bonus: 1, proficient: false },
    ],
    features: [
      "Sneak Attack: +3d6 damage when you have advantage",
      "Nimble Escape: Bonus action to Disengage or Hide",
      "Fury of the Small: Deal extra damage = your level (1/short rest)",
      "Evasion: Take no damage on successful DEX save (half on fail)",
      "Cunning Action: Bonus action Dash, Disengage, or Hide",
      "Uncanny Dodge: Use reaction to halve damage from an attack",
      "Darkvision: 60 ft",
    ],
    equipment: [
      "Two shortswords",
      "Shortbow with 20 arrows",
      "Studded leather armor",
      "Thieves' tools",
      "Gloves of Flame-Catching (catch and throw fire attacks)",
      "Flasks of oil (5)",
      "Grappling hook and rope",
    ],
    spells: {
      cantrips: [
        {
          name: "Fire Bolt",
          level: "Cantrip",
          castingTime: "1 action",
          range: "120 feet",
          components: "V, S",
          duration: "Instantaneous",
          description:
            "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack. On a hit, the target takes 2d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried.",
        },
        {
          name: "Mage Hand",
          level: "Cantrip",
          castingTime: "1 action",
          range: "30 feet",
          components: "V, S",
          duration: "1 minute",
          description:
            "A spectral, floating hand appears at a point you choose within range. The hand is invisible for Arcane Tricksters. You can use your action to control the hand, using it to manipulate objects, open unlocked doors, stow/retrieve items, or pick locks and disarm traps at range.",
        },
        {
          name: "Minor Illusion",
          level: "Cantrip",
          castingTime: "1 action",
          range: "30 feet",
          components: "S, M (bit of fleece)",
          duration: "1 minute",
          description:
            "You create a sound or an image of an object within range that lasts for the duration. The illusion ends if you dismiss it or cast the spell again. If you create a sound, its volume can range from a whisper to a scream. If you create an image of an object, it must be no larger than a 5-foot cube. The image can't create sound, light, smell, or other sensory effects. Physical interaction reveals it to be an illusion.",
        },
      ],
      level1: [
        {
          name: "Disguise Self",
          level: "1st-level",
          castingTime: "1 action",
          range: "Self",
          components: "V, S",
          duration: "1 hour",
          description:
            "You make yourself—including clothing, armor, weapons, and possessions—look different until the spell ends. You can seem 1 foot shorter or taller and appear thin, fat, or in between. You can't change your body type, so you must adopt a form that has the same basic arrangement of limbs. Physical inspection reveals the disguise.",
        },
        {
          name: "Grease",
          level: "1st-level",
          castingTime: "1 action",
          range: "60 feet",
          components: "V, S, M (butter or pork rind)",
          duration: "1 minute",
          description:
            "Slick grease covers the ground in a 10-foot square centered on a point within range. For the duration, it is difficult terrain. When the grease appears, each creature in the area must succeed on a Dexterity saving throw or fall prone. A creature that enters the area or ends its turn there must also make the save.",
        },
        {
          name: "Charm Person",
          level: "1st-level",
          castingTime: "1 action",
          range: "30 feet",
          components: "V, S",
          duration: "1 hour",
          description:
            "You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw, and does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance.",
        },
      ],
      level2: [
        {
          name: "Invisibility",
          level: "2nd-level",
          castingTime: "1 action",
          range: "Touch",
          components: "V, S, M (eyelash in gum arabic)",
          duration: "Concentration, up to 1 hour",
          description:
            "A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it's on the target's person. The spell ends for a target that attacks or casts a spell.",
        },
        {
          name: "Pyrotechnics",
          level: "2nd-level",
          castingTime: "1 action",
          range: "60 feet",
          components: "V, S",
          duration: "Instantaneous",
          description:
            "Choose an area of nonmagical flame within range that fits within a 5-foot cube. You can extinguish it, or create fireworks or smoke. Fireworks: Creatures within 10 feet must succeed on a Constitution save or be blinded until the end of your next turn. Smoke: Creates a 20-foot-radius sphere of smoke, heavily obscuring the area for 1 minute or until dispersed by wind.",
        },
      ],
    },
    spellSlots: {
      level1: { total: 4, available: 4 },
      level2: { total: 2, available: 2 },
    },
    spellSaveDC: 13,
    spellAttackBonus: 5,
    hitDie: 8,
    shortRestResources: [{ name: "Fury of the Small", uses: 1, restType: "short" }],
  },
  barenhal: {
    name: "Barenhal Everwatch",
    title: "The Watcher",
    theme: "theme-ranger",
    accentColor: "#34d399",
    accentColorRgb: "52, 211, 153",
    race: "Wood Elf",
    class: "Ranger",
    subclass: "Hunter",
    level: 6,
    alignment: "Lawful Good",
    abilities: {
      STR: 12,
      DEX: 18,
      CON: 14,
      INT: 12,
      WIS: 16,
      CHA: 10,
    },
    hp: 50,
    ac: 16,
    speed: 35,
    proficiencyBonus: 3,
    initiative: 4,
    savingThrows: {
      str: { bonus: 4, proficient: true },
      dex: { bonus: 7, proficient: true },
      con: { bonus: 2, proficient: false },
      int: { bonus: 1, proficient: false },
      wis: { bonus: 3, proficient: false },
      cha: { bonus: 0, proficient: false },
    },
    senses: ["Darkvision 60 ft.", "Passive Perception 19"],
    languages: ["Common", "Elvish", "Sylvan"],
    proficiencies: {
      armor: ["Light Armor", "Medium Armor", "Shields"],
      weapons: [
        "Simple Weapons",
        "Martial Weapons",
        "Longswords",
        "Shortswords",
        "Shortbows",
        "Longbows",
      ],
      tools: ["None"],
    },
    attacks: [
      {
        name: "Longbow",
        bonus: 8,
        damage: "1d8+6 piercing",
        notes: "Range 150/600, +2 Archery, Extra Attack, Colossus Slayer +1d8",
      },
      {
        name: "Shortsword",
        bonus: 7,
        damage: "1d6+4 piercing",
        notes: "Extra Attack",
      },
    ],
    skills: [
      { name: "Acrobatics", bonus: 4, proficient: false },
      { name: "Animal Handling", bonus: 3, proficient: false },
      { name: "Arcana", bonus: 1, proficient: false },
      { name: "Athletics", bonus: 4, proficient: true },
      { name: "Deception", bonus: 0, proficient: false },
      { name: "History", bonus: 1, proficient: false },
      { name: "Insight", bonus: 3, proficient: false },
      { name: "Intimidation", bonus: 0, proficient: false },
      { name: "Investigation", bonus: 4, proficient: true },
      { name: "Medicine", bonus: 3, proficient: false },
      { name: "Nature", bonus: 4, proficient: true },
      { name: "Perception", bonus: 9, proficient: true },
      { name: "Performance", bonus: 0, proficient: false },
      { name: "Persuasion", bonus: 0, proficient: false },
      { name: "Religion", bonus: 1, proficient: false },
      { name: "Sleight of Hand", bonus: 4, proficient: false },
      { name: "Stealth", bonus: 7, proficient: true },
      { name: "Survival", bonus: 9, proficient: true },
    ],
    features: [
      "Archery Fighting Style: +2 to ranged attack rolls",
      "Colossus Slayer: Extra 1d8 damage to damaged creatures (1/turn)",
      "Extra Attack: Attack twice per Attack action",
      "Favored Enemy: Advantage on tracking and Intelligence checks",
      "Natural Explorer: Double proficiency on Int/Wis checks in favored terrain",
      "Primeval Awareness: Detect aberrations, celestials, dragons, elementals, fey, fiends, undead",
      "Darkvision: 60 ft",
      "Mask of the Wild: Hide when lightly obscured",
      "Fleet of Foot: +5 ft movement speed",
    ],
    equipment: [
      "Longbow (+8 to hit, 1d8+6 damage)",
      "40 arrows",
      "Two shortswords",
      "Studded leather armor",
      "Eagle-Eye Sight (see up to 1 mile, advantage on first attack)",
      "Climber's kit",
      "Hunting trap",
    ],
    spells: {
      level1: [
        {
          name: "Hunter's Mark",
          level: "1st-level",
          castingTime: "1 bonus action",
          range: "90 feet",
          components: "V",
          duration: "Concentration, up to 1 hour",
          description:
            "You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack. Also, you have advantage on Wisdom (Perception) or Wisdom (Survival) checks to find it. If the target drops to 0 hit points, you can use a bonus action to mark a new creature.",
        },
        {
          name: "Cure Wounds",
          level: "1st-level",
          castingTime: "1 action",
          range: "Touch",
          components: "V, S",
          duration: "Instantaneous",
          description:
            "A creature you touch regains hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.",
        },
        {
          name: "Longstrider",
          level: "1st-level",
          castingTime: "1 action",
          range: "Touch",
          components: "V, S, M (pinch of dirt)",
          duration: "1 hour",
          description:
            "You touch a creature. The target's speed increases by 10 feet until the spell ends.",
        },
        {
          name: "Fog Cloud",
          level: "1st-level",
          castingTime: "1 action",
          range: "120 feet",
          components: "V, S",
          duration: "Concentration, up to 1 hour",
          description:
            "You create a 20-foot-radius sphere of fog centered on a point within range. The sphere spreads around corners, and its area is heavily obscured. It lasts for the duration or until a wind of moderate or greater speed disperses it.",
        },
      ],
      level2: [
        {
          name: "Pass Without Trace",
          level: "2nd-level",
          castingTime: "1 action",
          range: "Self",
          components: "V, S, M (ashes from burned mistletoe)",
          duration: "Concentration, up to 1 hour",
          description:
            "A veil of shadows and silence radiates from you, masking you and your companions from detection. For the duration, each creature you choose within 30 feet (including you) has a +10 bonus to Dexterity (Stealth) checks and can't be tracked except by magical means. A creature that receives this bonus leaves behind no tracks or other traces of its passage.",
        },
        {
          name: "Silence",
          level: "2nd-level",
          castingTime: "1 action (Ritual)",
          range: "120 feet",
          components: "V, S",
          duration: "Concentration, up to 10 minutes",
          ritual: true,
          description:
            "For the duration, no sound can be created within or pass through a 20-foot-radius sphere centered on a point you choose within range. Any creature or object entirely inside the sphere is immune to thunder damage, and creatures are deafened while entirely inside it. Casting a spell that includes a verbal component is impossible there.",
        },
      ],
    },
    spellSlots: {
      level1: { total: 4, available: 4 },
      level2: { total: 2, available: 2 },
    },
    spellSaveDC: 13,
    spellAttackBonus: 5,
    hitDie: 10,
  },
  karyl: {
    name: "Karyl",
    title: "The Heart",
    theme: "theme-fighter",
    accentColor: "#fb923c",
    accentColorRgb: "251, 146, 60",
    race: "Human",
    class: "Fighter",
    subclass: "Battle Master",
    level: 6,
    alignment: "Chaotic Good",
    abilities: {
      STR: 16,
      DEX: 14,
      CON: 16,
      INT: 8,
      WIS: 10,
      CHA: 14,
    },
    hp: 58,
    ac: 20,
    speed: 30,
    proficiencyBonus: 3,
    initiative: 2,
    savingThrows: {
      str: { bonus: 6, proficient: true },
      dex: { bonus: 2, proficient: false },
      con: { bonus: 6, proficient: true },
      int: { bonus: -1, proficient: false },
      wis: { bonus: 0, proficient: false },
      cha: { bonus: 2, proficient: false },
    },
    senses: ["Passive Perception 10"],
    languages: ["Common"],
    proficiencies: {
      armor: ["Light Armor", "Medium Armor", "Heavy Armor", "Shields"],
      weapons: ["Simple Weapons", "Martial Weapons"],
      tools: ["Playing Card Set"],
    },
    attacks: [
      {
        name: "Longsword",
        bonus: 6,
        damage: "1d8+3 slashing",
        notes: "Versatile: 1d10+3, Extra Attack, Maneuvers",
      },
      {
        name: "Javelin",
        bonus: 6,
        damage: "1d6+3 piercing",
        notes: "Range 30/120",
      },
    ],
    skills: [
      { name: "Acrobatics", bonus: 2, proficient: false },
      { name: "Animal Handling", bonus: 0, proficient: false },
      { name: "Arcana", bonus: -1, proficient: false },
      { name: "Athletics", bonus: 6, proficient: true },
      { name: "Deception", bonus: 2, proficient: false },
      { name: "History", bonus: -1, proficient: false },
      { name: "Insight", bonus: 0, proficient: false },
      { name: "Intimidation", bonus: 5, proficient: true },
      { name: "Investigation", bonus: -1, proficient: false },
      { name: "Medicine", bonus: 0, proficient: false },
      { name: "Nature", bonus: -1, proficient: false },
      { name: "Perception", bonus: 0, proficient: false },
      { name: "Performance", bonus: 5, proficient: true },
      { name: "Persuasion", bonus: 5, proficient: true },
      { name: "Religion", bonus: -1, proficient: false },
      { name: "Sleight of Hand", bonus: 2, proficient: false },
      { name: "Stealth", bonus: 2, proficient: false },
      { name: "Survival", bonus: 0, proficient: false },
    ],
    features: [
      "Combat Superiority: 4 superiority dice (d8)",
      "Maneuvers: Riposte, Goading Attack, Rally, Menacing Attack",
      "Second Wind: Regain 1d10+6 HP as bonus action (1/short rest)",
      "Action Surge: Take additional action (1/short rest)",
      "Extra Attack: Attack twice per Attack action",
      "Fighting Style: Defense (+1 AC while wearing armor)",
    ],
    maneuvers: [
      {
        name: "Riposte",
        description:
          "When a creature misses you with a melee attack, use your reaction and expend one superiority die to make a melee weapon attack against the creature. Add the superiority die to the damage roll.",
      },
      {
        name: "Goading Attack",
        description:
          "When you hit with a weapon attack, add superiority die to damage and target must make Wisdom save. On a fail, it has disadvantage on all attack rolls against targets other than you until the end of your next turn.",
      },
      {
        name: "Rally",
        description:
          "As a bonus action, expend a superiority die. Choose a friendly creature who can see or hear you. That creature gains temporary hit points equal to the die roll + your Charisma modifier. With Ring of the Inspiring Fool, also grants advantage on next attack.",
      },
      {
        name: "Menacing Attack",
        description:
          "When you hit with a weapon attack, add superiority die to damage and target must make Wisdom save. On a fail, it's frightened of you until the end of your next turn.",
      },
    ],
    equipment: [
      "Longsword",
      "Shield with personal emblem",
      "Plate armor",
      "Ring of the Inspiring Fool (Rally grants advantage; 1/long rest succeed on failed CHA check)",
      "Lucky coin",
      "Backpack with rations",
    ],
    hitDie: 10,
    shortRestResources: [
      { name: "Second Wind", uses: 1, restType: "short" },
      { name: "Action Surge", uses: 1, restType: "short" },
      { name: "Superiority Dice", uses: 4, restType: "short", die: "d8" },
    ],
  },
}
