const characters = {
  amox: {
    name: "Amox Velthune",
    title: "The Lore Keeper",
    theme: "theme-wizard",
    accentColor: "#8b7dd8",
    accentColorRgb: "139, 125, 216",
    race: "Half-Elf",
    class: "Wizard",
    subclass: "School of Divination",
    level: 6,
    alignment: "Lawful Neutral",
    abilities: {
      STR: 8,
      DEX: 14,
      CON: 14,
      INT: 18,
      WIS: 12,
      CHA: 8,
    },
    hp: 38,
    ac: 12,
    speed: 30,
    proficiencyBonus: 3,
    initiative: 2,
    savingThrows: {
      str: { bonus: -1, proficient: false },
      dex: { bonus: 2, proficient: false },
      con: { bonus: 2, proficient: false },
      int: { bonus: 7, proficient: true },
      wis: { bonus: 4, proficient: true },
      cha: { bonus: -1, proficient: false },
    },
    senses: ["Darkvision 60 ft.", "Passive Perception 14"],
    languages: ["Common", "Elvish", "Draconic", "Dwarvish"],
    proficiencies: {
      armor: ["None"],
      weapons: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
      tools: ["None"],
    },
    attacks: [
      {
        name: "Quarterstaff",
        bonus: -1,
        damage: "1d6-1 bludgeoning",
        notes: "Two-handed: 1d8-1",
      },
      {
        name: "Fire Bolt (cantrip)",
        bonus: 7,
        damage: "2d10 fire",
        notes: "Ranged spell attack, 120 ft.",
      },
    ],
    skills: [
      { name: "Acrobatics", bonus: 2, proficient: false },
      { name: "Animal Handling", bonus: 1, proficient: false },
      { name: "Arcana", bonus: 7, proficient: true },
      { name: "Athletics", bonus: -1, proficient: false },
      { name: "Deception", bonus: -1, proficient: false },
      { name: "History", bonus: 7, proficient: true },
      { name: "Insight", bonus: 4, proficient: true },
      { name: "Intimidation", bonus: -1, proficient: false },
      { name: "Investigation", bonus: 7, proficient: true },
      { name: "Medicine", bonus: 1, proficient: false },
      { name: "Nature", bonus: 4, proficient: false },
      { name: "Perception", bonus: 4, proficient: true },
      { name: "Performance", bonus: -1, proficient: false },
      { name: "Persuasion", bonus: -1, proficient: false },
      { name: "Religion", bonus: 4, proficient: false },
      { name: "Sleight of Hand", bonus: 2, proficient: false },
      { name: "Stealth", bonus: 2, proficient: false },
      { name: "Survival", bonus: 1, proficient: false },
    ],
    features: [
      "Portent: Roll 2d20 after long rest, replace any roll during the day",
      "Arcane Recovery: Recover spell slots during short rest (up to level 3)",
      "Darkvision: 60 ft",
      "Fey Ancestry: Advantage vs charm, immune to sleep magic",
      "Ritual Casting: Cast wizard spells as rituals",
    ],
    equipment: [
      "Spellbook",
      "Arcane focus (crystal orb)",
      "Lens of Translation (advantage on ancient texts)",
      "Component pouch",
      "Dagger",
      "Scholar's pack",
    ],
    spells: {
      cantrips: [
        { id: "fire-bolt" },
        { id: "mage-hand" },
        { id: "prestidigitation" },
        { id: "message" },
      ],
      level1: [
        { id: "detect-magic" },
        { id: "identify" },
        { id: "comprehend-languages" },
        { id: "mage-armor" },
        { id: "shield" },
        { id: "find-familiar" },
      ],
      level2: [
        { id: "detect-thoughts" },
        { id: "locate-object" },
        { id: "misty-step" },
        { id: "suggestion" },
      ],
      level3: [
        { id: "counterspell" },
        { id: "fireball" },
        { id: "dispel-magic" },
        { id: "clairvoyance" },
      ],
    },
    spellSlots: {
      level1: { total: 4, available: 4 },
      level2: { total: 3, available: 3 },
      level3: { total: 3, available: 3 },
    },
    spellSaveDC: 15,
    spellAttackBonus: 7,
    hitDie: 6,
    shortRestResources: [
      { name: "Portent Dice", uses: 2, restType: "long" },
      { name: "Arcane Recovery", uses: 1, restType: "long" },
    ],
  },
  barak: {
    name: "Barak",
    title: "The Anchor",
    theme: "theme-cleric",
    accentColor: "#f59e0b",
    accentColorRgb: "245, 158, 11",
    race: "Mountain Dwarf",
    class: "Cleric",
    subclass: "Life Domain",
    level: 6,
    alignment: "Lawful Good",
    abilities: {
      STR: 16,
      DEX: 10,
      CON: 16,
      INT: 10,
      WIS: 16,
      CHA: 12,
    },
    hp: 52,
    ac: 18,
    speed: 25,
    proficiencyBonus: 3,
    initiative: 0,
    savingThrows: {
      str: { bonus: 3, proficient: false },
      dex: { bonus: 0, proficient: false },
      con: { bonus: 6, proficient: true },
      int: { bonus: 0, proficient: false },
      wis: { bonus: 6, proficient: true },
      cha: { bonus: 4, proficient: true },
    },
    senses: ["Darkvision 60 ft.", "Passive Perception 13"],
    languages: ["Common", "Dwarvish"],
    proficiencies: {
      armor: ["Light Armor", "Medium Armor", "Heavy Armor", "Shields"],
      weapons: ["Simple Weapons", "Battleaxe", "Handaxe", "Light Hammer", "Warhammer"],
      tools: ["Smith's Tools", "Brewer's Supplies", "Mason's Tools"],
    },
    attacks: [
      {
        name: "Warhammer",
        bonus: 6,
        damage: "1d8+3 bludgeoning",
        notes: "Versatile: 1d10+3",
      },
      {
        name: "Sacred Flame (cantrip)",
        bonus: null,
        damage: "2d8 radiant",
        notes: "DEX save DC 14, 60 ft.",
      },
    ],
    skills: [
      { name: "Acrobatics", bonus: 0, proficient: false },
      { name: "Animal Handling", bonus: 3, proficient: false },
      { name: "Arcana", bonus: 0, proficient: false },
      { name: "Athletics", bonus: 6, proficient: true },
      { name: "Deception", bonus: 1, proficient: false },
      { name: "History", bonus: 0, proficient: false },
      { name: "Insight", bonus: 6, proficient: true },
      { name: "Intimidation", bonus: 1, proficient: false },
      { name: "Investigation", bonus: 0, proficient: false },
      { name: "Medicine", bonus: 6, proficient: true },
      { name: "Nature", bonus: 0, proficient: false },
      { name: "Perception", bonus: 3, proficient: false },
      { name: "Performance", bonus: 1, proficient: false },
      { name: "Persuasion", bonus: 1, proficient: false },
      { name: "Religion", bonus: 3, proficient: true },
      { name: "Sleight of Hand", bonus: 0, proficient: false },
      { name: "Stealth", bonus: 0, proficient: false },
      { name: "Survival", bonus: 3, proficient: false },
    ],
    features: [
      "Disciple of Life: Healing spells restore +2 + spell level HP",
      "Channel Divinity: Preserve Life (30 HP pool to distribute)",
      "Channel Divinity: Turn Undead",
      "Destroy Undead (CR 1/2 or lower)",
      "Darkvision: 60 ft",
      "Dwarven Resilience: Advantage vs poison, resistance to poison damage",
    ],
    equipment: [
      "Warhammer",
      "Shield with holy symbol",
      "Chain mail",
      "Amulet of the Steadfast (reduce to 1 HP instead of 0, 1/long rest)",
      "Holy symbol",
      "Prayer book",
      "Healer's kit",
    ],
    spells: {
      cantrips: [{ id: "sacred-flame" }, { id: "spare-the-dying" }, { id: "guidance" }],
      level1: [
        { id: "cure-wounds" },
        { id: "healing-word" },
        { id: "bless", level: "1st-level (Domain)" },
        { id: "shield-of-faith" },
      ],
      level2: [
        { id: "spiritual-weapon" },
        { id: "lesser-restoration", level: "2nd-level (Domain)" },
        { id: "aid" },
      ],
      level3: [
        { id: "revivify", level: "3rd-level (Domain)" },
        { id: "beacon-of-hope", level: "3rd-level (Domain)" },
        { id: "spirit-guardians" },
      ],
    },
    spellSlots: {
      level1: { total: 4, available: 4 },
      level2: { total: 3, available: 3 },
      level3: { total: 3, available: 3 },
    },
    spellSaveDC: 14,
    spellAttackBonus: 6,
    hitDie: 8,
    shortRestResources: [{ name: "Channel Divinity", uses: 2, restType: "short" }],
  },
  tenoch: {
    name: "Tenoch",
    title: "The Silent Guardian",
    theme: "theme-paladin",
    accentColor: "#60a5fa",
    accentColorRgb: "96, 165, 250",
    race: "Goliath",
    class: "Paladin",
    subclass: "Oath of Redemption",
    level: 6,
    alignment: "Neutral Good",
    abilities: {
      STR: 16,
      DEX: 10,
      CON: 16,
      INT: 8,
      WIS: 12,
      CHA: 14,
    },
    hp: 58,
    ac: 18,
    speed: 30,
    proficiencyBonus: 3,
    initiative: 0,
    savingThrows: {
      str: { bonus: 3, proficient: false },
      dex: { bonus: 0, proficient: false },
      con: { bonus: 3, proficient: false },
      int: { bonus: -1, proficient: false },
      wis: { bonus: 4, proficient: true },
      cha: { bonus: 5, proficient: true },
    },
    senses: ["Passive Perception 11"],
    languages: ["Common", "Giant"],
    proficiencies: {
      armor: ["Light Armor", "Medium Armor", "Heavy Armor", "Shields"],
      weapons: ["Simple Weapons", "Martial Weapons"],
      tools: ["None"],
    },
    attacks: [
      {
        name: "Maul",
        bonus: 6,
        damage: "2d6+3 bludgeoning",
        notes: "Two-handed, heavy",
      },
    ],
    skills: [
      { name: "Acrobatics", bonus: 0, proficient: false },
      { name: "Animal Handling", bonus: 1, proficient: false },
      { name: "Arcana", bonus: -1, proficient: false },
      { name: "Athletics", bonus: 6, proficient: true },
      { name: "Deception", bonus: 2, proficient: false },
      { name: "History", bonus: -1, proficient: false },
      { name: "Insight", bonus: 4, proficient: true },
      { name: "Intimidation", bonus: 2, proficient: false },
      { name: "Investigation", bonus: -1, proficient: false },
      { name: "Medicine", bonus: 4, proficient: true },
      { name: "Nature", bonus: -1, proficient: false },
      { name: "Perception", bonus: 1, proficient: false },
      { name: "Performance", bonus: 2, proficient: false },
      { name: "Persuasion", bonus: 5, proficient: true },
      { name: "Religion", bonus: -1, proficient: false },
      { name: "Sleight of Hand", bonus: 0, proficient: false },
      { name: "Stealth", bonus: 0, proficient: false },
      { name: "Survival", bonus: 1, proficient: false },
    ],
    features: [
      "Stone's Endurance: Reduce damage by 1d12+3 (1/short rest)",
      "Protection Fighting Style: Impose disadvantage on attack against ally",
      "Lay on Hands: 30 HP healing pool",
      "Divine Smite: Expend spell slot for extra radiant damage",
      "Aura of Protection: +2 to saving throws for allies within 10 ft",
      "Rebuke the Violent: Reflect damage back to attacker",
      "Powerful Build: Count as one size larger for carrying capacity",
    ],
    equipment: [
      "Maul",
      "Shield with protective runes",
      "Chain mail",
      "Bracers of Shielding (teleport to ally and grant resistance, 1/long rest)",
      "Holy symbol",
      "Healing potions (2)",
    ],
    spells: {
      level1: [
        { id: "sanctuary", level: "1st-level (Oath)" },
        { id: "sleep", level: "1st-level (Oath)" },
        { id: "bless" },
        { id: "shield-of-faith" },
      ],
      level2: [
        { id: "hold-person", level: "2nd-level (Oath)" },
        { id: "calm-emotions", level: "2nd-level (Oath)" },
        { id: "aid" },
      ],
    },
    spellSlots: {
      level1: { total: 4, available: 4 },
      level2: { total: 2, available: 2 },
    },
    spellSaveDC: 13,
    spellAttackBonus: 5,
    hitDie: 10,
    shortRestResources: [
      { name: "Stone's Endurance", uses: 1, restType: "short" },
      { name: "Lay on Hands", uses: 30, restType: "long", pool: true },
    ],
  },
  glorg: {
    name: "Glorg",
    title: "The Wildfire",
    theme: "theme-rogue",
    accentColor: "#f87171",
    accentColorRgb: "248, 113, 113",
    race: "Goblin",
    class: "Rogue",
    subclass: "Arcane Trickster",
    level: 6,
    alignment: "Chaotic Good",
    abilities: {
      STR: 8,
      DEX: 18,
      CON: 14,
      INT: 14,
      WIS: 12,
      CHA: 10,
    },
    hp: 40,
    ac: 16,
    speed: 30,
    proficiencyBonus: 3,
    initiative: 4,
    savingThrows: {
      str: { bonus: -1, proficient: false },
      dex: { bonus: 7, proficient: true },
      con: { bonus: 2, proficient: false },
      int: { bonus: 5, proficient: true },
      wis: { bonus: 1, proficient: false },
      cha: { bonus: 0, proficient: false },
    },
    senses: ["Darkvision 60 ft.", "Passive Perception 14"],
    languages: ["Common", "Goblin"],
    proficiencies: {
      armor: ["Light Armor"],
      weapons: ["Simple Weapons", "Hand Crossbows", "Longswords", "Rapiers", "Shortswords"],
      tools: ["Thieves' Tools"],
    },
    attacks: [
      {
        name: "Shortsword (melee)",
        bonus: 7,
        damage: "1d6+4 piercing",
        notes: "Sneak Attack: +3d6",
      },
      {
        name: "Shortsword (offhand)",
        bonus: 7,
        damage: "1d6+4 piercing",
        notes: "Two-weapon fighting",
      },
      {
        name: "Shortbow",
        bonus: 7,
        damage: "1d6+4 piercing",
        notes: "Range 80/320, Sneak Attack: +3d6",
      },
    ],
    skills: [
      { name: "Acrobatics", bonus: 7, proficient: true },
      { name: "Animal Handling", bonus: 1, proficient: false },
      { name: "Arcana", bonus: 2, proficient: false },
      { name: "Athletics", bonus: -1, proficient: false },
      { name: "Deception", bonus: 3, proficient: true },
      { name: "History", bonus: 2, proficient: false },
      { name: "Insight", bonus: 1, proficient: false },
      { name: "Intimidation", bonus: 0, proficient: false },
      { name: "Investigation", bonus: 5, proficient: true },
      { name: "Medicine", bonus: 1, proficient: false },
      { name: "Nature", bonus: 2, proficient: false },
      { name: "Perception", bonus: 4, proficient: true },
      { name: "Performance", bonus: 0, proficient: false },
      { name: "Persuasion", bonus: 0, proficient: false },
      { name: "Religion", bonus: 2, proficient: false },
      { name: "Sleight of Hand", bonus: 7, proficient: true },
      { name: "Stealth", bonus: 10, proficient: true },
      { name: "Survival", bonus: 1, proficient: false },
    ],
    features: [
      "Sneak Attack: +3d6 damage when you have advantage",
      "Nimble Escape: Bonus action to Disengage or Hide",
      "Fury of the Small: Deal extra damage = your level (1/short rest)",
      "Evasion: Take no damage on successful DEX save (half on fail)",
      "Cunning Action: Bonus action Dash, Disengage, or Hide",
      "Uncanny Dodge: Use reaction to halve damage from an attack",
      "Darkvision: 60 ft",
    ],
    equipment: [
      "Two shortswords",
      "Shortbow with 20 arrows",
      "Studded leather armor",
      "Thieves' tools",
      "Gloves of Flame-Catching (catch and throw fire attacks)",
      "Flasks of oil (5)",
      "Grappling hook and rope",
    ],
    spells: {
      cantrips: [
        { id: "fire-bolt" },
        {
          id: "mage-hand",
          description:
            "A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again.\n\nYou can use your action to control the hand. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial. You can move the hand up to 30 feet each time you use it.\n\nThe hand can't attack, activate magic items, or carry more than 10 pounds. As an Arcane Trickster, your mage hand is invisible and can also stow or retrieve items from another creature's pockets, pick locks, and disarm traps.",
        },
        { id: "minor-illusion" },
      ],
      level1: [{ id: "disguise-self" }, { id: "grease" }, { id: "charm-person" }],
      level2: [{ id: "invisibility" }, { id: "pyrotechnics" }],
    },
    spellSlots: {
      level1: { total: 4, available: 4 },
      level2: { total: 2, available: 2 },
    },
    spellSaveDC: 13,
    spellAttackBonus: 5,
    hitDie: 8,
    shortRestResources: [{ name: "Fury of the Small", uses: 1, restType: "short" }],
  },
  barenhal: {
    name: "Barenhal Everwatch",
    title: "The Watcher",
    theme: "theme-ranger",
    accentColor: "#34d399",
    accentColorRgb: "52, 211, 153",
    race: "Wood Elf",
    class: "Ranger",
    subclass: "Hunter",
    level: 6,
    alignment: "Lawful Good",
    abilities: {
      STR: 12,
      DEX: 18,
      CON: 14,
      INT: 12,
      WIS: 16,
      CHA: 10,
    },
    hp: 50,
    ac: 16,
    speed: 35,
    proficiencyBonus: 3,
    initiative: 4,
    savingThrows: {
      str: { bonus: 4, proficient: true },
      dex: { bonus: 7, proficient: true },
      con: { bonus: 2, proficient: false },
      int: { bonus: 1, proficient: false },
      wis: { bonus: 3, proficient: false },
      cha: { bonus: 0, proficient: false },
    },
    senses: ["Darkvision 60 ft.", "Passive Perception 19"],
    languages: ["Common", "Elvish", "Sylvan"],
    proficiencies: {
      armor: ["Light Armor", "Medium Armor", "Shields"],
      weapons: [
        "Simple Weapons",
        "Martial Weapons",
        "Longswords",
        "Shortswords",
        "Shortbows",
        "Longbows",
      ],
      tools: ["None"],
    },
    attacks: [
      {
        name: "Longbow",
        bonus: 8,
        damage: "1d8+6 piercing",
        notes: "Range 150/600, +2 Archery, Extra Attack, Colossus Slayer +1d8",
      },
      {
        name: "Shortsword",
        bonus: 7,
        damage: "1d6+4 piercing",
        notes: "Extra Attack",
      },
    ],
    skills: [
      { name: "Acrobatics", bonus: 4, proficient: false },
      { name: "Animal Handling", bonus: 3, proficient: false },
      { name: "Arcana", bonus: 1, proficient: false },
      { name: "Athletics", bonus: 4, proficient: true },
      { name: "Deception", bonus: 0, proficient: false },
      { name: "History", bonus: 1, proficient: false },
      { name: "Insight", bonus: 3, proficient: false },
      { name: "Intimidation", bonus: 0, proficient: false },
      { name: "Investigation", bonus: 4, proficient: true },
      { name: "Medicine", bonus: 3, proficient: false },
      { name: "Nature", bonus: 4, proficient: true },
      { name: "Perception", bonus: 9, proficient: true },
      { name: "Performance", bonus: 0, proficient: false },
      { name: "Persuasion", bonus: 0, proficient: false },
      { name: "Religion", bonus: 1, proficient: false },
      { name: "Sleight of Hand", bonus: 4, proficient: false },
      { name: "Stealth", bonus: 7, proficient: true },
      { name: "Survival", bonus: 9, proficient: true },
    ],
    features: [
      "Archery Fighting Style: +2 to ranged attack rolls",
      "Colossus Slayer: Extra 1d8 damage to damaged creatures (1/turn)",
      "Extra Attack: Attack twice per Attack action",
      "Favored Enemy: Advantage on tracking and Intelligence checks",
      "Natural Explorer: Double proficiency on Int/Wis checks in favored terrain",
      "Primeval Awareness: Detect aberrations, celestials, dragons, elementals, fey, fiends, undead",
      "Darkvision: 60 ft",
      "Mask of the Wild: Hide when lightly obscured",
      "Fleet of Foot: +5 ft movement speed",
    ],
    equipment: [
      "Longbow (+8 to hit, 1d8+6 damage)",
      "40 arrows",
      "Two shortswords",
      "Studded leather armor",
      "Eagle-Eye Sight (see up to 1 mile, advantage on first attack)",
      "Climber's kit",
      "Hunting trap",
    ],
    spells: {
      level1: [
        { id: "hunters-mark" },
        { id: "cure-wounds" },
        { id: "longstrider" },
        { id: "fog-cloud" },
      ],
      level2: [{ id: "pass-without-trace" }, { id: "silence" }],
    },
    spellSlots: {
      level1: { total: 4, available: 4 },
      level2: { total: 2, available: 2 },
    },
    spellSaveDC: 13,
    spellAttackBonus: 5,
    hitDie: 10,
  },
  karyl: {
    name: "Karyl",
    title: "The Heart",
    theme: "theme-fighter",
    accentColor: "#fb923c",
    accentColorRgb: "251, 146, 60",
    race: "Human",
    class: "Fighter",
    subclass: "Battle Master",
    level: 6,
    alignment: "Chaotic Good",
    abilities: {
      STR: 16,
      DEX: 14,
      CON: 16,
      INT: 8,
      WIS: 10,
      CHA: 14,
    },
    hp: 58,
    ac: 20,
    speed: 30,
    proficiencyBonus: 3,
    initiative: 2,
    savingThrows: {
      str: { bonus: 6, proficient: true },
      dex: { bonus: 2, proficient: false },
      con: { bonus: 6, proficient: true },
      int: { bonus: -1, proficient: false },
      wis: { bonus: 0, proficient: false },
      cha: { bonus: 2, proficient: false },
    },
    senses: ["Passive Perception 10"],
    languages: ["Common"],
    proficiencies: {
      armor: ["Light Armor", "Medium Armor", "Heavy Armor", "Shields"],
      weapons: ["Simple Weapons", "Martial Weapons"],
      tools: ["Playing Card Set"],
    },
    attacks: [
      {
        name: "Longsword",
        bonus: 6,
        damage: "1d8+3 slashing",
        notes: "Versatile: 1d10+3, Extra Attack, Maneuvers",
      },
      {
        name: "Javelin",
        bonus: 6,
        damage: "1d6+3 piercing",
        notes: "Range 30/120",
      },
    ],
    skills: [
      { name: "Acrobatics", bonus: 2, proficient: false },
      { name: "Animal Handling", bonus: 0, proficient: false },
      { name: "Arcana", bonus: -1, proficient: false },
      { name: "Athletics", bonus: 6, proficient: true },
      { name: "Deception", bonus: 2, proficient: false },
      { name: "History", bonus: -1, proficient: false },
      { name: "Insight", bonus: 0, proficient: false },
      { name: "Intimidation", bonus: 5, proficient: true },
      { name: "Investigation", bonus: -1, proficient: false },
      { name: "Medicine", bonus: 0, proficient: false },
      { name: "Nature", bonus: -1, proficient: false },
      { name: "Perception", bonus: 0, proficient: false },
      { name: "Performance", bonus: 5, proficient: true },
      { name: "Persuasion", bonus: 5, proficient: true },
      { name: "Religion", bonus: -1, proficient: false },
      { name: "Sleight of Hand", bonus: 2, proficient: false },
      { name: "Stealth", bonus: 2, proficient: false },
      { name: "Survival", bonus: 0, proficient: false },
    ],
    features: [
      "Combat Superiority: 4 superiority dice (d8)",
      "Maneuvers: Riposte, Goading Attack, Rally, Menacing Attack",
      "Second Wind: Regain 1d10+6 HP as bonus action (1/short rest)",
      "Action Surge: Take additional action (1/short rest)",
      "Extra Attack: Attack twice per Attack action",
      "Fighting Style: Defense (+1 AC while wearing armor)",
    ],
    maneuvers: [
      {
        name: "Riposte",
        description:
          "When a creature misses you with a melee attack, use your reaction and expend one superiority die to make a melee weapon attack against the creature. Add the superiority die to the damage roll.",
      },
      {
        name: "Goading Attack",
        description:
          "When you hit with a weapon attack, add superiority die to damage and target must make Wisdom save. On a fail, it has disadvantage on all attack rolls against targets other than you until the end of your next turn.",
      },
      {
        name: "Rally",
        description:
          "As a bonus action, expend a superiority die. Choose a friendly creature who can see or hear you. That creature gains temporary hit points equal to the die roll + your Charisma modifier. With Ring of the Inspiring Fool, also grants advantage on next attack.",
      },
      {
        name: "Menacing Attack",
        description:
          "When you hit with a weapon attack, add superiority die to damage and target must make Wisdom save. On a fail, it's frightened of you until the end of your next turn.",
      },
    ],
    equipment: [
      "Longsword",
      "Shield with personal emblem",
      "Plate armor",
      "Ring of the Inspiring Fool (Rally grants advantage; 1/long rest succeed on failed CHA check)",
      "Lucky coin",
      "Backpack with rations",
    ],
    hitDie: 10,
    shortRestResources: [
      { name: "Second Wind", uses: 1, restType: "short" },
      { name: "Action Surge", uses: 1, restType: "short" },
      { name: "Superiority Dice", uses: 4, restType: "short", die: "d8" },
    ],
  },
}
